name: "🐛 Bug Report"
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
      placeholder: "When I run memory_search, it returns..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - MCP Server
        - Hooks (UserPrompt/PreTool/PostTool)
        - Embedding Server
        - LLM Server
        - Memory DB / Search
        - Clustering
        - Configuration
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "e.g. 20.11.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Windows (WSL)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant logs or error messages
      render: shell
